[package]
name = "Disk-Mosaic"
version = "0.2.1"
edition.workspace = true
build = "build.rs"
authors.workspace = true
description = "Disk Mosaic is a disk utility helping you to identify biggest folders"
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories = ["filesystem", "visualization"]
exclude = [
    ".cargo-husky/",
    ".github/",
    ".idea/",
    ".junie",
]

[workspace.package]
authors = ["Matthieu Casanova"]
edition = "2024"
license = "MIT"
keywords = ["desktop", "file", "folder", "disk"]
homepage = "https://github.com/kpouer/Disk-Mosaic"
repository = "https://github.com/kpouer/Disk-Mosaic"
readme = "README.md"

[[bin]]
name = "dm"
path = "src/tui_app.rs"
required-features = ["tui"]

[[bin]]
name = "DiskMosaic"
path = "src/gui_app.rs"
required-features = ["gui"]

[dependencies]
clap = { version = "4.6", features = ["derive"] }
env_logger = "0.11"
disk-mosaic-gui = { path = "crates/disk-mosaic-gui", version = "0.1.0", optional = true }
disk-mosaic-tui = { path = "crates/disk-mosaic-tui", version = "0.1.0", optional = true }

[workspace.dependencies]
ecolor = "0.34"
egui = "0.34"
egui_extras = "0.34"
eframe = "0.34"
home = "0.5.12"
log = "0.4"
treemap = "0.3.2"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
members = [
    "crates/disk-mosaic-core",
    "crates/disk-mosaic-gui",
    "crates/disk-mosaic-tui",
]

[features]
default = []
gui = [
    "dep:disk-mosaic-gui",
]
tui = [
    "dep:disk-mosaic-tui",
]

[profile.release]
codegen-units = 1
opt-level = 2
lto = true

[package.metadata.bundle]
name = "DiskMosaic"
identifier = "com.kpouer.diskmosaic"
icon = ["packaging/DiskMosaic.app/Contents/Resources/AppIcon.icns"]
version = "0.1.4"
copyright = "Copyright (c) 2025-2026 Matthieu Casanova"
category = "Utility"
short_description = "Disk Mosaic is a disk utility helping you to identify biggest folders"
resources = [
    "assets",
    "media",
    "LICENSE",
    "README.md"
]
