[package]
name = "DiskMosaic"
version = "0.2.0"
edition = "2024"
build = "build.rs"
authors = ["Matthieu Casanova"]
description = "Disk Mosaic is a disk utility helping you to identify biggest folders"
homepage = "https://github.com/kpouer/Disk-Mosaic"
repository = "https://github.com/kpouer/Disk-Mosaic"
license = "MIT"
readme = "README.md"
keywords = ["desktop", "file", "folder", "disk"]
categories = ["filesystem"]

[[bin]]
name = "dm"
path = "src/main.rs"
required-features = ["tui"]

[[bin]]
name = "DiskMosaic"
path = "src/main.rs"
required-features = ["gui"]

[dependencies]
clap = { version = "4.6", features = ["derive"] }
env_logger = "0.11"
disk-mosaic-gui = { path = "crates/disk-mosaic-gui", optional = true }
disk-mosaic-tui = { path = "crates/disk-mosaic-tui", optional = true }

[workspace.dependencies]
home = "0.5.12"
log = "0.4"
treemap = "0.3.2"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
members = [
    "crates/disk-mosaic-core",
    "crates/disk-mosaic-gui",
    "crates/disk-mosaic-tui",
]

[features]
default = []
gui = [
    "dep:disk-mosaic-gui",
]
tui = [
    "dep:disk-mosaic-tui",
]

[profile.release]
codegen-units = 1
opt-level = 2
lto = true

[package.metadata.bundle]
name = "DiskMosaic"
identifier = "com.kpouer.diskmosaic"
icon = ["packaging/DiskMosaic.app/Contents/Resources/AppIcon.icns"]
version = "0.1.4"
copyright = "Copyright (c) 2025-2026 Matthieu Casanova"
category = "Utility"
short_description = "Disk Mosaic is a disk utility helping you to identify biggest folders"
resources = [
    "assets",
    "media",
    "LICENSE",
    "README.md"
]
