[package]
name = "disk-mosaic-core"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
description = "This is a library used for Terminal User Interface of https://crates.io/crates/Disk-Mosaic"
readme = "README.md"

[dependencies]
log = { workspace = true }
rayon = "1.12.0"
thiserror = "2.0"
treemap = { workspace = true }
unicode-normalization = "0.1.25"
